# Squirrelsong Dark Theme for WezTerm
# https://sapegin.me/squirrelsong/

[colors]
foreground = '#bea3d9'
background = '#271e38'

cursor_bg = '#bea3d9'
cursor_fg = '#271e38'
cursor_border = '#bea3d9'

selection_fg = '#bea3d9'
selection_bg = '#4c3c6b'

split = '#453461'

visual_bell = "#ca5a83"

ansi = [
  '#644e88',
  '#ac493e',
  '#558240',
  '#ceb250',
  '#5993c2',
  '#7f61b3',
  '#4f9593',
  '#bea3d9',
]

brights = [
  '#7254a6',
  '#ca5a83',
  '#709855',
  '#e2c358',
  '#63a2d6',
  '#9672d4',
  '#72aaa8',
  '#e9d6fa',
]

[colors.tab_bar]
# Retro tab bar
background = '#271e38'
# Fancy tab bar
inactive_tab_edge = '#271e38'

[colors.tab_bar.active_tab]
bg_color = '#503f6e'
fg_color = '#bea3d9'
intensity = 'Bold'

[colors.tab_bar.inactive_tab]
bg_color = '#271e38'
fg_color = '#bea3d9'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#453461'
fg_color = '#bea3d9'

[colors.tab_bar.new_tab]
bg_color = '#271e38'
fg_color = '#bea3d9'

[colors.tab_bar.new_tab_hover]
bg_color = '#453461'
fg_color = '#bea3d9'

[metadata]
aliases = []
author = 'Artem Sapegin'
name = 'Squirrelsong Dark'
