# Squirrelsong {{name}} Theme for WezTerm
# https://sapegin.me/squirrelsong/

[colors]
foreground = '{{foreground}}'
background = '{{background}}'

cursor_bg = '{{foreground}}'
cursor_fg = '{{background}}'
cursor_border = '{{foreground}}'

selection_fg = '{{foreground}}'
selection_bg = '{{selectionBackground}}'

split = '{{lightBorder}}'

visual_bell = "{{brightRed}}"

ansi = [
  '{{black}}',
  '{{red}}',
  '{{green}}',
  '{{yellow}}',
  '{{blue}}',
  '{{magenta}}',
  '{{cyan}}',
  '{{white}}',
]

brights = [
  '{{brightBlack}}',
  '{{brightRed}}',
  '{{brightGreen}}',
  '{{brightYellow}}',
  '{{brightBlue}}',
  '{{brightMagenta}}',
  '{{brightCyan}}',
  '{{brightWhite}}',
]

[colors.tab_bar]
# Retro tab bar
background = '{{background}}'
# Fancy tab bar
inactive_tab_edge = '{{background}}'

[colors.tab_bar.active_tab]
bg_color = '{{activeBackground}}'
fg_color = '{{activeForeground}}'
intensity = 'Bold'

[colors.tab_bar.inactive_tab]
bg_color = '{{background}}'
fg_color = '{{foreground}}'

[colors.tab_bar.inactive_tab_hover]
bg_color = '{{hoverBackground}}'
fg_color = '{{foreground}}'

[colors.tab_bar.new_tab]
bg_color = '{{background}}'
fg_color = '{{foreground}}'

[colors.tab_bar.new_tab_hover]
bg_color = '{{hoverBackground}}'
fg_color = '{{foreground}}'

[metadata]
aliases = []
author = 'Artem Sapegin'
name = 'Squirrelsong {{name}}'
