# Squirrelsong {{name}} Theme for WezTerm
# https://sapegin.me/squirrelsong/

[colors]
foreground = '{{terminalForeground}}'
background = '{{terminalBackground}}'

cursor_bg = '{{terminalForeground}}'
cursor_fg = '{{terminalBackground}}'
cursor_border = '{{terminalForeground}}'

selection_fg = '{{terminalForeground}}'
selection_bg = '{{selectionBackground}}'

split = '{{lightBorder}}'

visual_bell = "{{terminalBrightRed}}"

ansi = [
  '{{terminalBlack}}',
  '{{terminalRed}}',
  '{{terminalGreen}}',
  '{{terminalYellow}}',
  '{{terminalBlue}}',
  '{{terminalMagenta}}',
  '{{terminalCyan}}',
  '{{terminalWhite}}',
]

brights = [
  '{{terminalBrightBlack}}',
  '{{terminalBrightRed}}',
  '{{terminalBrightGreen}}',
  '{{terminalBrightYellow}}',
  '{{terminalBrightBlue}}',
  '{{terminalBrightMagenta}}',
  '{{terminalBrightCyan}}',
  '{{terminalBrightWhite}}',
]

[colors.tab_bar]
# Retro tab bar
background = '{{terminalBackground}}'
# Fancy tab bar
inactive_tab_edge = '{{terminalBackground}}'

[colors.tab_bar.active_tab]
bg_color = '{{activeBackground}}'
fg_color = '{{activeForeground}}'
intensity = 'Bold'

[colors.tab_bar.inactive_tab]
bg_color = '{{terminalBackground}}'
fg_color = '{{terminalForeground}}'

[colors.tab_bar.inactive_tab_hover]
bg_color = '{{hoverBackground}}'
fg_color = '{{terminalForeground}}'

[colors.tab_bar.new_tab]
bg_color = '{{terminalBackground}}'
fg_color = '{{terminalForeground}}'

[colors.tab_bar.new_tab_hover]
bg_color = '{{hoverBackground}}'
fg_color = '{{terminalForeground}}'

[metadata]
aliases = []
author = 'Artem Sapegin'
name = 'Squirrelsong {{name}}'
