{
  "base": {
    "text color": "#4c4b4e",
    "text secondary color": "#78737d",
    "text tertiary color": "#9c96a2",
    "background color": "#fdfdfe",
    "background secondary color": "#f7f6f9",
    "background tertiary color": "#e8e5eb",
    "background hover color": "#e8e5eb",
    "stroke color": "#e8e5eb",
    "accent color": "#78737d",
    "icon color": "#8c8792",
    "dark icon color": "#78737d",
    "search primary color": "#e87da4",
    "search secondary color": "#fae1ea",
    "highlight color": "#e9d9a8",
    "selection color": "#f5da70"
  },
  "notes": {
    "title color": "$base.text color",
    "subtitle color": "$base.text secondary color",
    "placeholder color": "$base.text secondary color",
    "date color": "$base.text secondary color",
    "pin color": "$base.icon color",
    "separator color": "$base.background tertiary color",
    "search background color": "$base.search secondary color",
    "attachment background color": "$base.background secondary color",
    "encrypted token color": "$base.background secondary color",
    "selection background color": "$base.background hover color",
    "ribbon color": "$base.icon color",
    "toolbar": {
      "background color": "$base.background color",
      "text color": "$base.text color",
      "icon color": "$base.icon color",
      "hover color": "$base.background hover color"
    }
  },
  "sidebar": {
    "text color": "$base.text color",
    "text secondary color": "$base.text color",
    "background color": "$base.background secondary color",
    "background secondary color": "#dbd7e0",
    "stroke color": "$base.stroke color",
    "accent color": "#dbd7e0",
    "icon color": "$base.icon color",
    "selected icon color": "$base.dark icon color",
    "toolbar": {
      "background color": "$base.background secondary color",
      "icon color": "$base.icon color",
      "hover color": "$base.background hover color"
    }
  },
  "placeholder": {
    "background color": "$base.background color",
    "background stroke color": "#e8e5eb",
    "shadow color": "#f7f6f9",
    "stroke color": "#9c96a2"
  },
  "editor": {
    "background color": "$base.background color",
    "text color": "$base.text color",
    "text light color": "$base.text secondary color",
    "accent color": "$base.accent color",
    "cursor color": "#6b676f",
    "link color": "#527b98",
    "list marker color": "#9c96a2",
    "marker color": "#9c96a2",
    "selection color": "$base.selection color",
    "selection inactive color": "$base.background tertiary color",
    "text font": "BearSansUI-Regular",
    "text size": 15,
    "line height multiplier": 1.5,
    "headers": {
      "text color": "#4c4b4e",
      "font": "BearSansUIHeadline-Regular",
      "modular scale": 1.125,
      "line height multiplier": 1.3,
      "add top bottom padding": 1,
      "padding top multiplier": 0.5,
      "padding bottom multiplier": 0.3
    },
    "code": {
      "text color": "#78737d",
      "border color": "transparent",
      "background color": "$base.background secondary color",
      "font": "MonoLisa",
      "syntax highlight": {
        "comment": "#9c96a2",
        "constant": "#80a4be",
        "number": "#de9e59",
        "string": "#9bae7e",
        "entity": "#5f9b8d",
        "keyword": "#ac9bc5",
        "function": "#80a4be",
        "variable": "#80a4be"
      }
    },
    "task": {
      "background color": "$base.background color",
      "border color": "#9c96a2",
      "check color": "#9c96a2"
    },
    "tag": {
      "background color": "#e8e5eb",
      "text color": "#78737d",
      "marker color": "#a8a1af"
    },
    "highlighter": {
      "background color": "$base.highlight color",
      "text color": "$base.text color"
    },
    "separator": {
      "border color": "#c9c4cf"
    },
    "table": {
      "border color": "$base.stroke color",
      "cell background color": "$base.background color",
      "cell alternate background color": "$base.background secondary color"
    },
    "toolbar": {
      "icon color": "$base.icon color",
      "hover color": "$base.background hover color"
    }
  }
}
