{
  "base": {
    "text color": "#4c4b4e",
    "text secondary color": "#78737d",
    "text tertiary color": "#9c96a2",
    "background color": "#fdfdfe",
    "background secondary color": "#f7f6f9",
    "background tertiary color": "#e8e5eb",
    "background hover color": "#e8e5eb",
    "stroke color": "#e8e5eb",
    "accent color": "#4c4b4e",
    "icon color": "#8c8792",
    "dark icon color": "#4c4b4e",
    "search primary color": "#f0a8c2",
    "search secondary color": "#fae1ea",
    "selection color": "#f8e7a0"
  },
  "notes": {
    "title color": "#4c4b4e",
    "subtitle color": "#78737d",
    "placeholder color": "#78737d",
    "date color": "#78737d",
    "pin color": "#8c8792",
    "separator color": "#e8e5eb",
    "search background color": "#fae1ea",
    "attachment background color": "#f7f6f9",
    "encrypted token color": "#f7f6f9",
    "selection background color": "#e8e5eb",
    "ribbon color": "#8c8792",
    "toolbar": {
      "background color": "#fdfdfe",
      "text color": "#4c4b4e",
      "icon color": "#8c8792",
      "hover color": "#e8e5eb"
    }
  },
  "sidebar": {
    "text color": "#78737d",
    "text secondary color": "#4c4b4e",
    "background color": "#f7f6f9",
    "background secondary color": "#dbd7e0",
    "stroke color": "#e8e5eb",
    "accent color": "#dbd7e0",
    "icon color": "#8c8792",
    "selected icon color": "#4c4b4e",
    "toolbar": {
      "background color": "#f7f6f9",
      "icon color": "#8c8792",
      "hover color": "#e8e5eb"
    }
  },
  "placeholder": {
    "background color": "#fdfdfe",
    "background stroke color": "#e8e5eb",
    "shadow color": "#f7f6f9",
    "stroke color": "#9c96a2"
  },
  "editor": {
    "background color": "#fdfdfe",
    "text color": "#4c4b4e",
    "text light color": "#78737d",
    "accent color": "#4c4b4e",
    "cursor color": "#4c4b4e",
    "link color": "#4b7b97",
    "list marker color": "#9c96a2",
    "marker color": "#9c96a2",
    "selection color": "#f8e7a0",
    "selection inactive color": "#fdf6de",
    "text font": "BearSansUI-Regular",
    "text size": 15,
    "line height multiplier": 1.5,
    "headers": {
      "text color": "#4c4b4e",
      "font": "BearSansUIHeadline-Regular",
      "modular scale": 1.125,
      "line height multiplier": 1.3,
      "add top bottom padding": 1,
      "padding top multiplier": 0.5,
      "padding bottom multiplier": 0.3
    },
    "code": {
      "text color": "#78737d",
      "border color": "transparent",
      "background color": "#f7f6f9",
      "font": "MonoLisa",
      "syntax highlight": {
        "comment": "#9c96a2",
        "constant": "#80a4be",
        "number": "#de9e59",
        "string": "#9bae7e",
        "entity": "#5f9b8d",
        "keyword": "#ac9bc5",
        "function": "#80a4be",
        "variable": "#80a4be"
      }
    },
    "task": {
      "background color": "#fdfdfe",
      "border color": "#c9c4cf",
      "check color": "#c9c4cf"
    },
    "tag": {
      "background color": "#e8e5eb",
      "text color": "#6b676f",
      "marker color": "#8c8792"
    },
    "highlighter": {
      "background color": "#e8d8a5",
      "text color": "#4c4b4e"
    },
    "separator": {
      "border color": "#c9c4cf"
    },
    "table": {
      "border color": "#e8e5eb",
      "cell background color": "#fdfdfe",
      "cell alternate background color": "#f7f6f9"
    },
    "toolbar": {
      "icon color": "#8c8792",
      "hover color": "#e8e5eb"
    }
  }
}
