name "Squirrelsong Light"

base {
    appearance "light"
    background #f7f6f9
    separator #9c96a2
    text #4c4b4e
}

actionBar {
    button {
        background #e8e5eb
        hotkey #78737d
        text #78737d
    }
}

asyncProgressBar {
    border #8c8792
    progress #4c4b4e
    itemProgress #8c8792
}

breadcrumbs {
    separator #9c96a2
    text #4c4b4e
    background #fdfdfe
}

files {
    background {
        alternate #fdfdfe
        current #9c96a2
        currentSelected #9c96a2
        selected #fae1ea
    }

    dragDropSelection {
        color #78737d
        width 0
    }

    text {
        current #f7f6f9
        currentSelected #fae1ea
        hidden #78737d
        matched #e87da4
        selected #e87da4

        highlighting1 #527b98
        highlighting2 #667e44
        highlighting3 #e4c158
        highlighting4 #ac9bc5
    }
}

searchBar {
    material "light"

    query {
        background #e8e5eb
        placeholder #e8e5eb
        text #78737d
    }

    results {
        highlighting #78737d
        selection #dbd7e0
        subtitle #78737d
        text #78737d
    }

    rowSeparator {
        color #e8e5eb
        show false
    }
}

statusBar {
    background #e8e5eb
    text #78737d
    quickSelectNoResultsHighlighting #e5ada8
    separator #9c96a2
}

tableHeader {
    separator #9c96a2
    text #78737d

    pressed {
        background #e8e5eb
    }
}

tabs {
    background #e8e5eb

    active {
        background #fdfdfe
        text #78737d
    }

    inactive {
        background #e8e5eb
        text #78737d
    }
}

terminal {
    caret {
        background #78737d
        text #fdfdfe
    }
}

textEditor {
    error #d67e76
    warning #e4c158
    keyword #c06159
    comment #9c96a2
    identifier #f7f0de

    literal {
        string #9bae7e
        number #527b98
        color #bfd1de
    }

    gutter {
        background #e8e5eb
        text #e5ada866
    }
}

titleBar {
    text #4c4b4e
}
