# name: {{name}}
# description: {{description}}
# author: Artem Sapegin

chroma-style = {{chromaStyle}}
color-accent = {{accent}}
color-border = {{border}}
color-normal = {{terminalForeground}}
color-muted = {{secondaryTextForeground}}
color-selected-fg = {{terminalForeground}}
color-selected-bg = {{selectionBackground}}
color-annotation = {{warningForeground}}
color-cursor-fg = {{accent}}
{{cursorBackground}}
color-add-fg = {{successForeground}}
color-add-bg = {{insertedBackground}}
color-remove-fg = {{errorForeground}}
color-remove-bg = {{deletedBackground}}
color-word-add-bg = {{insertedWordBackground}}
color-word-remove-bg = {{deletedWordBackground}}
color-modify-fg = {{warningForeground}}
color-modify-bg = {{warningBackground}}
{{treeBackground}}
color-diff-bg = {{textBackground}}
{{statusColors}}
color-search-fg = {{matchForeground}}
color-search-bg = {{matchBackground}}
