# Squirrelsong {{name}} Theme for Ghostty
# https://sapegin.me/squirrelsong/

foreground = {{terminalForeground}}
background = {{terminalBackground}}
selection-foreground = {{terminalForeground}}
selection-background = {{selectionBackground}}
cursor-color = {{terminalForeground}}

# Black
palette = 0={{terminalBlack}}
palette = 8={{terminalBrightBlack}}

# Red
palette = 1={{terminalRed}}
palette = 9={{terminalBrightRed}}

# Green
palette = 2={{terminalGreen}}
palette = 10={{terminalBrightGreen}}

# Yellow
palette = 3={{terminalYellow}}
palette = 11={{terminalBrightYellow}}

# Blue
palette = 4={{terminalBlue}}
palette = 12={{terminalBrightBlue}}

# Magenta
palette = 5={{terminalMagenta}}
palette = 13={{terminalBrightMagenta}}

# Cyan
palette = 6={{terminalCyan}}
palette = 14={{terminalBrightCyan}}

# White
palette = 7={{terminalWhite}}
palette = 15={{terminalBrightWhite}}

# Use Squirrelsong colors for the icon
macos-icon-ghost-color = {{iconForeground}}
macos-icon-screen-color = {{iconBackground}}
