# Squirrelsong ${name} Theme for Ghostty
# https://sapegin.me/squirrelsong/

foreground = ${foreground}
background = ${background}
selection-foreground = ${foreground}
selection-background = ${selection}
cursor-color = ${foreground}

# Black
palette = 0=${black}
palette = 8=${brightBlack}

# Red
palette = 1=${red}
palette = 9=${brightRed}

# Green
palette = 2=${green}
palette = 10=${brightGreen}

# Yellow
palette = 3=${yellow}
palette = 11=${brightYellow}

# Blue
palette = 4=${blue}
palette = 12=${brightBlue}

# Magenta
palette = 5=${magenta}
palette = 13=${brightMagenta}

# Cyan
palette = 6=${cyan}
palette = 14=${brightCyan}

# White
palette = 7=${white}
palette = 15=${brightWhite}

# Use Squirrelsong colors for the icon
macos-icon-ghost-color = ${iconForeground}
macos-icon-screen-color = ${iconBackground}
