Description="Squirrelsong {{name}}"

Categories = {"{{category}}"}

Default = { Colour="{{textForeground}}" }
Canvas = { Colour="{{textBackground}}" }
Number = { Colour="{{value}}" }
String = { Colour="{{string}}" }
Escape = { Colour="{{escapeCharacter}}", Bold=true }
PreProcessor = { Colour="{{string}}" }
StringPreProc = { Colour="{{string}}" }
BlockComment = { Colour="{{comment}}" }
LineComment = { Colour="{{comment}}" }
LineNum = { Colour="{{secondaryTextForeground}}" }
Operator = { Colour="{{operator}}" }
Interpolation = { Colour="{{escapeCharacter}}", Bold=true }
Hover = { Colour="", Custom = { { Format = "html", Style = "cursor:help;", Override = false } } }
Error = { Colour="{{deleted}}" }
ErrorMessage = { Colour="{{errorForeground}}", Custom = { { Format = "html", Style = "border:solid 1px red; margin-left: 3em;", Override = false } } }

Keywords = {
	{ Colour="{{keyword}}", Bold=true },
	{ Colour="{{type}}" },
	{ Colour="{{keyword}}" },
	{ Colour="{{function}}" },
	{ Colour="{{type}}" },
	{ Colour="{{deleted}}" }
}


SemanticTokenTypes = {
	{ Type = 'keyword', Style = { Colour="{{keyword}}", Bold=true } },
	{ Type = 'type', Style = { Colour="{{type}}" } },
	{ Type = 'function', Style = { Colour="{{function}}", Bold=true } },
	{ Type = 'method', Style = { Colour="{{function}}" } },
	{ Type = 'class', Style = { Colour="{{function}}", Bold=true } },
	{ Type = 'struct', Style = { Colour="{{type}}" } },
	{ Type = 'parameter', Style = { Colour="{{property}}" } },
	{ Type = 'variable', Style = { Colour="{{variable}}", Italic=true } },
	{ Type = 'number', Style = { Colour="{{value}}" } },
	{ Type = 'regexp', Style = { Colour="{{string}}" } },
	{ Type = 'operator', Style = { Colour="{{operator}}" } },
}
